### ISSUE TITLE
alignment issue

### ISSUE THREAD

**Issue by SeleDreams** [devkitPro/ndstool#12]
Hi, I'm posting this issue because I ended up being affected by an issue that seems caused by ndstool not properly interpreting the data of the elf
I basically have an application written in rust that generates an elf binary for the arm7 including some sections before the preinit_array sections, as we can see here
![image](https://user-images.githubusercontent.com/16335601/218533776-039dc969-6d62-4b94-aef9-81d9281b88f3.png)

and  I've been told that because debug_gdb_script is 22 bytes long, the rest ends up misaligned

here's the arm7 elf 
[fifo_example.zip](https://github.com/devkitPro/ndstool/files/10724886/fifo_example.zip)

i'm not too sure how i would be able to fix this, do you have any idea ?

**Comment by WinterMute** [comment]
In what way does ndstool not properly interpret the data of the elf?

**Comment by SeleDreams** [comment]
![Capture d’écran du 2023-02-13 19-32-22](https://user-images.githubusercontent.com/16335601/218544246-100d65de-db32-45b0-a87a-db144bf69606.png)
I am not too experienced at it but i think this message describes better the issue

**Comment by SeleDreams** [comment]
this causes my program to work in release mode but not in debug mode once the gdb sections are added

**Comment by SeleDreams** [comment]
I ended up being able to fix my issue by setting "emit-debug-gdb-scripts" to false in my rust target settings
