### ISSUE TITLE
Allow configuring more settings in the SRL header.

### ISSUE THREAD

**Issue by ApacheThunder** [devkitPro/ndstool#2]
There are various fields in the NTR Header/DSi exheader that interfere with the operation of certain homebrew when used on 3DS in legacy mode (via TWL_FIRM). Because CFW exists for this console, it is possible to launch homebrew directly in a manner similar to proper DSiWare.

As a result certain settings in the header become important.

The following regions I suggest should be allowed to be customized. (though ndstool can continue to use what it uses as the default values as they will work fine for most projects):

NTR Header region:
Region 0x13:

Currently ndstool hardcodes this to 02 which sets the rom to launch in DSi Enhanced mode. While this has no impact on homebrew started via hbmenu/in a hax environment like sudokuhax, it is however a minor problem on 3DS. It is non standard for non slot-1 applications to use this mode and can interfere with card init when access control region of header is not set to power slot-1 in ntr mode. This currently is only relevent to versions of Nitrohax ported to work on 3DS and NTR Launcher which is setup to launch DS games from slot-1. Currently have to manually edit the SRL to use 03 instead as would be expected for DSiWare apps installed to NAND.

Region 0x1C:

This appears to have no functional impact on homebrew right now, but it is an inconsistency with official software. ndstool currently sets this to 03. According to known header documentation on both gbatek and other sources ndstool is setting bit1. This enables modcrypt for the rom. However this is not correct. Homebrew compiled with devkitarm r46 does not currently use modcrypt for DSi arm9/arm7 binaries. Bit1 should not be set. So correct code for this region should be 01 instead of 03 as it is now. This issue is low priority however as it appears to not actually break anything on 3DS when launched directly as DSiWare.

DSi Extended Header region:

Region 0x1B4: 
The default value ndstool hardcodes here enables ntr mode for slot-1. This is bit5 as to the documentation I've read for this region. Though a lot of this isn't well understood yet. But from my experienced, setting this bit is required for homebrew booted from SD/NAND on 3DS to use DLDI with a cart used in slot1. So in most circumstances the default values used here is fine. However card init doesn't work as a result of this. It would be nice to be able to configure at least bit5 from ndstool as some homebrew like NitroHax work better with this off on 3DS so that card init can occur without ejecting/reinserting the card. (as you can not do that on a 3DS or a DSi for that matter).

Region 0x1BF:

ndstool hardcodes this to 01. This causes issues with programs that would want to switch into NTR mode later on. NitroHax ported to work on 3DS is one notable example. This region appears to impact what compatibility mode touchscreen is in. If set to 01 as ndstool does, it uses DSi compatibility touchscreen so libnds inits touchscreen correctly.

However for a program like NitroHax, this causes problems. Any games booted from Nitrohax will not have working touchscreen controls because the SRL that booted them was initially booted with DSi touchscreen set. It is not documented how this is actually toggled on hardware, but the only known way for now is via at boot via that header option.

This is more of a libnds issue then a ndstool issue. libnds should be updated to detect the correct state of touchscreen before attempting to init them. Perhaps a function can be added to force NTR compatibility touchscreen code regardless of what mode the program started in. If changing the mode of the touchscreen becomes possible later on then I guess this option may be less relevant, so it's low priority for ndstool.

Either way, being able to adjust this region will be required in certain applications.

**Comment by WinterMute** [comment]
This has no relation to ndstool, sorry.
