### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by vadixidav** [devkitPro/ndstool#4]
I am considering building and packaging a nds filesystem interface for Rust using this code base. One option is to have a user acquire the exe and another is to package the source with the crate, but either way I would like it if there was a license explicitly granting permission to use and redistribute the source and executable like the MIT license. Right now there is no license, but would you mind adding an open source license to allow the source to be redistributed? Thanks for your consideration.

**Comment by mtheall** [comment]
By "nds filesystem" do you mean nitrofs, i.e. romfs?

**Comment by vadixidav** [comment]
@Aissurteivos

**Comment by mtheall** [comment]
You can use this code if you like: https://github.com/mtheall/nitrofs-fuse

**Comment by vadixidav** [comment]
I talked with @Aissurteivos about it, as it is something we were discussing (I was calling him out to respond earlier). It seems you have a pretty clean implementation of the filesystem traversal. Would you mind if we wrote a Rust implementation based on your code? We are going to making a GUI, so we want a library to achieve the filesystem reading rather than mounting it with fuse, but your code basically shows exactly what to do for our purposes.

**Comment by vadixidav** [comment]
Also, to be clear, the reason I'm asking is to ensure I have permission, since you don't currently have a license either.

**Comment by mtheall** [comment]
Look at the COPYING file.

I wrote that code about 4 years ago and with a quick review I found some very minor bugs which I opened issues for tracking.

**Comment by vadixidav** [comment]
Would you consider licensing it under a permissive license? Typically Rust crates build statically. It's fine if not, but it might allow the audience to be wider.

**Comment by mtheall** [comment]
GPLv3 doesn't prevent you from distributing static builds. Rust crates are no stranger to it either.

**Comment by vadixidav** [comment]
True, but I was concerned about how it might affect downstream consumers. I will just GPLv3 license my code in that case.

**Comment by WinterMute** [comment]
This seems resolved
